### PR TITLE
Improvements to attributeReportingConfig and fix to saving settings for TH01/SNZB-02/SNZB-02D/SNZB-02P/ZBMINI-L

### PR DESCRIPTION
**Pull request by Boechie**
Fixed issues #17 and #18:
* Saving settings for TH01/SNZB-02/SNZB-02D/SNZB-02P devices fixed
* Solved unnecessary zigbee messages for TH01/SNZB-02/SNZB-02D/SNZB-02P/ZBMINI-L devices

### CODE REVIEW

**Review by Boechie — COMMENTED** [review]
Hello @JohanBendz . Could you please review (and accept) my PR? I tried to give code explanations bij review comments. If anything is unclear, please let me know.

To my colleagues @manarINW, @ayhamdabbas, @mihaiINW: If you have any comments on my work, please make review comments.

**Comment by JohanBendz** [comment]
Hi @Boechie, thanks for the PR.
I'll have a look at it this weekend!

**Comment by Boechie** [comment]
Hi @JohanBendz.

Did you have the opportunity to look at this PR? I'm happy to explain my changes or make any new changes if necessary.

> Hi @Boechie, thanks for the PR. I'll have a look at it this weekend!

**Comment by JohanBendz** [comment]
Hi @Boechie, ooops.. sorry for letting this hang.. been busy with other apps and life in general :(
I'll have a look at it asap.

**Comment by JohanBendz** [comment]
Thanks for the PR @Boechie, everything looks good. I like how you think :)

**Comment by Boechie** [comment]
@JohanBendz I think many of my changes could also be applied to other Sonoff devices, but as I don't have those devices I can't test it. Therefore I didn't make those changes.

Furthermore I think that this PR also solves issue https://github.com/JohanBendz/tech.sonoff/issues/21.

**Pull request merged**
